### ISSUE TITLE
Missing formats

### ISSUE THREAD

**Issue by 89z** [alexitx/pythumb#1]
I see some here:

https://github.com/alexitx/pythumb/blob/6e6956891cd514e878dde35c5948680ecffd2605/pythumb/core.py#L61-L67

but some others are available:

- https://i.ytimg.com/vi/iTBW6jbHgX0/0.jpg
- https://i.ytimg.com/vi/iTBW6jbHgX0/1.jpg
- https://i.ytimg.com/vi/iTBW6jbHgX0/2.jpg
- https://i.ytimg.com/vi/iTBW6jbHgX0/3.jpg
- https://i.ytimg.com/vi/iTBW6jbHgX0/sd1.jpg
- https://i.ytimg.com/vi/iTBW6jbHgX0/sd2.jpg
- https://i.ytimg.com/vi/iTBW6jbHgX0/sd3.jpg

**Comment by alexitx** [comment]
After a bit of searching it turns out there are 3 generated thumbnails for every size, except `maxresdefault`:
`maxresdefault`
`sddefault` -> `sd1`, `sd2`, `sd3`
`hqdefault` -> `hq1`, `hq2`, `hq3`
`mqdefault` -> `mq1`, `mq2`, `mq3`
`default` -> `1`, `2`, `3`

I'm not sure if the other 3 images are always available or whether all have webp variants, but it will be nice to have them as an option.

There seem to be some inconsistencies though:
- [`mq1`](https://i.ytimg.com/vi/aqz-KE-bpKQ/mq1.jpg) and [`mq2`](https://i.ytimg.com/vi/aqz-KE-bpKQ/mq2.jpg) return the same image of `aqz-KE-bpKQ`
- `hq1` has the first and second image swapped compared to the other sizes:
[`hq1`](https://i.ytimg.com/vi/aqz-KE-bpKQ/hq1.jpg) -> [`sd2`](https://i.ytimg.com/vi/aqz-KE-bpKQ/sd2.jpg)
[`hq2`](https://i.ytimg.com/vi/aqz-KE-bpKQ/hq2.jpg) -> [`sd1`](https://i.ytimg.com/vi/aqz-KE-bpKQ/sd1.jpg)
- `0` is the same as `hqdefault`, but that seems like it's intended. Since both return bit-exact image, maybe we should just always use `hqdefault`?

The fallback mechanism might be better to only try 'default' thumbnails (i.e. `maxresdefault`, `sddefault`, not `sd1`, `sd2`, etc) because those are the official/main thumbnails set by the creator, while the others are (randomly?) generated from the start, middle and end of the video. I'm planning to rewrite some things soon and will perhaps include enum class with all sizes allowing any size/variant to be chosen.

Let me know if you have any suggestions

**Comment by 89z** [comment]
If it helps, I am working on a similar project in Go. Here is the full list from my testing:

~~~go
{left:"hq", right:"1", ext:"jpg"},
{left:"hq", right:"2", ext:"jpg"},
{left:"hq", right:"3", ext:"jpg"},
{left:"hq", right:"720", ext:"jpg"},
{left:"hq", right:"default", ext:"jpg"},
{left:"maxres", right:"1", ext:"jpg"},
{left:"maxres", right:"2", ext:"jpg"},
{left:"maxres", right:"3", ext:"jpg"},
{left:"maxres", right:"default", ext:"jpg"},
{left:"mq", right:"1", ext:"jpg"},
{left:"mq", right:"2", ext:"jpg"},
{left:"mq", right:"3", ext:"jpg"},
{left:"mq", right:"default", ext:"jpg"},
{left:"sd", right:"1", ext:"jpg"},
{left:"sd", right:"2", ext:"jpg"},
{left:"sd", right:"3", ext:"jpg"},
{left:"sd", right:"default", ext:"jpg"},
{right:"0", ext:"jpg"},
{right:"1", ext:"jpg"},
{right:"2", ext:"jpg"},
{right:"3", ext:"jpg"},
{right:"default", ext:"jpg"},
{vi:"_webp", left:"hq", right:"1", ext:"webp"},
{vi:"_webp", left:"hq", right:"2", ext:"webp"},
{vi:"_webp", left:"hq", right:"3", ext:"webp"},
{vi:"_webp", left:"hq", right:"720", ext:"webp"},
{vi:"_webp", left:"hq", right:"default", ext:"webp"},
{vi:"_webp", left:"maxres", right:"1", ext:"webp"},
{vi:"_webp", left:"maxres", right:"2", ext:"webp"},
{vi:"_webp", left:"maxres", right:"3", ext:"webp"},
{vi:"_webp", left:"maxres", right:"default", ext:"webp"},
{vi:"_webp", left:"mq", right:"1", ext:"webp"},
{vi:"_webp", left:"mq", right:"2", ext:"webp"},
{vi:"_webp", left:"mq", right:"3", ext:"webp"},
{vi:"_webp", left:"mq", right:"default", ext:"webp"},
{vi:"_webp", left:"sd", right:"1", ext:"webp"},
{vi:"_webp", left:"sd", right:"2", ext:"webp"},
{vi:"_webp", left:"sd", right:"3", ext:"webp"},
{vi:"_webp", left:"sd", right:"default", ext:"webp"},
{vi:"_webp", right:"0", ext:"webp"},
{vi:"_webp", right:"1", ext:"webp"},
{vi:"_webp", right:"2", ext:"webp"},
{vi:"_webp", right:"3", ext:"webp"},
{vi:"_webp", right:"default", ext:"webp"},
~~~

**Comment by alexitx** [comment]
Thank you, that would be very helpful. I didn't test thoroughly, so I'll also include `maxres*`.

**Comment by alexitx** [comment]
ac7a8227a071c8b10078698fc70ed062423edbe3
